name: Godot Export Windows

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - debug
      release_tag:
        description: 'Release tag (only for release builds)'
        required: false
        type: string
        default: 'v1.0.0'

jobs:
  export-windows:
    name: Export for Windows (${{ github.event.inputs.build_type }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Godot executable
        uses: chickensoft-games/setup-godot@v1
        with:
          version: '4.4.1'
          use-mono: true

      - name: Install Export Templates from Repository
        run: |
          GODOT_VERSION="4.4.1"
          TEMPLATE_DIR="/home/runner/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono"
          mkdir -p "${TEMPLATE_DIR}"
          echo "Copying templates from ExportTemplates/ directory..."
          cp ExportTemplates/windows_debug_x86_64.exe "${TEMPLATE_DIR}/"
          cp ExportTemplates/windows_release_x86_64.exe "${TEMPLATE_DIR}/"

      - name: Check for Export Templates
        run: |
          echo "Checking for templates in /home/runner/.local/share/godot/export_templates/4.4.1.stable.mono/"
          ls -la /home/runner/.local/share/godot/export_templates/4.4.1.stable.mono/ || echo "Directory not found or empty."

      - name: Export Godot project (Release)
        if: github.event.inputs.build_type == 'release'
        run: |
          mkdir -p artifacts/windows-build-release
          godot --headless --export-release "Windows Desktop" artifacts/windows-build-release/Explosive-Outplay_${{ github.event.inputs.release_tag }}.exe .

      - name: Export Godot project (Debug)
        if: github.event.inputs.build_type == 'debug'
        run: |
          mkdir -p artifacts/windows-build-debug
          godot --headless --export-debug "Windows Desktop" artifacts/windows-build-debug/Explosive-Outplay_debug.exe .

      - name: Create GitHub Release and Upload (Release)
        if: github.event.inputs.build_type == 'release'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: Release ${{ github.event.inputs.release_tag }}
          files: |
            artifacts/windows-build-release/Explosive-Outplay_${{ github.event.inputs.release_tag }}.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Artifact (Debug)
        if: github.event.inputs.build_type == 'debug'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-debug
          path: artifacts/windows-build-debug