# Nama workflow yang akan tampil di tab Actions GitHub
name: Godot Export Windows

# Pemicu (trigger) kapan workflow ini akan dijalankan
on:
  push:
    branches: [ master ] # Jalankan saat ada push ke branch 'master' atau 'main'
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual dari tab Actions

jobs:
  export-windows:
    # Nama job (bisa lebih dari satu job dalam satu workflow)
    name: Export for Windows
    # Tentukan runner (mesin virtual) yang akan digunakan
    runs-on: ubuntu-latest # Menggunakan Ubuntu, karena setup-godot menangani environment

    steps:
      # Langkah 1: Checkout kode proyek Anda dari repositori
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true # Tambahkan ini jika Anda menggunakan Git LFS untuk aset besar

      # Langkah 2: Setup Godot Export (menggunakan action komunitas)
      # Action ini akan mengunduh Godot dan template ekspor yang diperlukan
      - name: Set up Godot export templates
        uses: chickensoft-games/setup-godot@v1
        with:
          version: '4.4.1' # Pastikan ini versi Godot yang Anda gunakan
          use-mono: true   # Aktifkan ini karena Anda menggunakan versi Mono/C#
          # Optional: tentukan cache untuk mempercepat build berikutnya
          # cache-key-prefix: ${{ github.job }}-${{ runner.os }}

      # Langkah 3: Ekspor Proyek Godot untuk Windows Desktop
      - name: Export Godot project
        # Ganti 'GameDev2025_GroupProject' jika nama folder proyek Anda berbeda
        # Ganti 'YourGameName.exe' dengan nama executable yang Anda inginkan
        run: |
          mkdir -p artifacts/windows-build  # Buat direktori output di root repo
          godot --headless --export-release "Windows Desktop" ../artifacts/windows-build/YourGameName.exe .

      # Langkah 4: Upload Artifact (hasil build)
      # Menyimpan file hasil build agar bisa diunduh dari halaman Actions
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build # Nama artifact yang akan muncul di GitHub
          path: artifacts/windows-build # Path ke folder yang berisi hasil build (.exe dan .pck) relatif ke root repo