# Nama workflow yang akan tampil di tab Actions GitHub
name: Godot Export Windows

# Pemicu (trigger) kapan workflow ini akan dijalankan
on:
  push:
    branches: [ master ] # Jalankan saat ada push ke branch 'master' atau 'main'
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual dari tab Actions

jobs:
  export-windows:
    # Nama job (bisa lebih dari satu job dalam satu workflow)
    name: Export for Windows
    # Tentukan runner (mesin virtual) yang akan digunakan
    runs-on: ubuntu-latest # Menggunakan Ubuntu, karena setup-godot menangani environment
# ... (previous parts of the workflow) ...

    steps:
      # Langkah 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true # Tambahkan ini jika Anda menggunakan Git LFS untuk aset besar

      # Langkah 2: Setup Godot Export (menggunakan action komunitas)
      - name: Set up Godot export templates
        uses: chickensoft-games/setup-godot@v1
        with:
          version: '4.4.1' # Pastikan ini versi Godot yang Anda gunakan
          use-mono: true   # Aktifkan ini karena Anda menggunakan versi Mono/C#
          # Optional: Disable cache if suspecting issues (uncomment next line)
          # cache-disabled: true

      # DEBUG: List contents of expected template directory
      - name: Check for Export Templates
        run: |
          echo "Checking for templates in /home/runner/.local/share/godot/export_templates/4.4.1.stable.mono/"
          ls -la /home/runner/.local/share/godot/export_templates/4.4.1.stable.mono/ || echo "Directory not found or empty."

      # Langkah 3: Ekspor Proyek Godot untuk Windows Desktop
      - name: Export Godot project
        # Ganti 'YourGameName.exe' dengan nama executable yang Anda inginkan
        # Asumsi project.godot ada di root repo
        run: |
          mkdir -p artifacts/windows-build  # Buat direktori output di root repo
          # Corrected output path (no '../')
          godot --headless --export-release "Windows Desktop" artifacts/windows-build/YourGameName.exe .

      # Langkah 4: Upload Artifact (hasil build)
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build # Nama artifact yang akan muncul di GitHub
          path: artifacts/windows-build # Path ke folder yang berisi hasil build (.exe dan .pck) relatif ke root repo

# ... (rest of the workflow if any) ...